import {useEffect,useRef,useState} from 'react';
import {type LiveRun} from './LivePerformance';
export default function LiveHumanEval({onResult}:{onResult?:(run:LiveRun)=>void}){
 const [run,setRun]=useState<LiveRun|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
 useEffect(()=>{if(run)onResult?.(run)},[run,onResult]);
 useEffect(()=>{const id=new URL(window.location.href).searchParams.get('liveRun');if(id&&/^[a-f0-9-]{36}$/.test(id))void fetch('/api/live?id='+id).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.message||j.error);setRun(j)}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(run?.id&&/^[a-f0-9-]{36}$/.test(run.id)){const url=new URL(window.location.href);url.searchParams.set('liveRun',run.id);window.history.replaceState(null,'',url);}},[run?.id]);
 async function start(text?:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{let taskIds;if(text){const parsed=JSON.parse(text);if(!Array.isArray(parsed))throw Error('HumanEval 문제 배열이 필요합니다.');taskIds=parsed.map(p=>p.task_id);}const r=await fetch('/api/live',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskIds})});const j=await r.json();if(!r.ok)throw Error(j.message||j.error);setRun(j);}catch(e){setError(e instanceof Error?e.message:'실행 실패')}finally{lock.current=false;setBusy(false)}}
 useEffect(()=>{const f=(e:Event)=>{void start((e as CustomEvent<string>).detail)};window.addEventListener('atlas-live-run',f);return()=>window.removeEventListener('atlas-live-run',f)},[]);
 useEffect(()=>{if(!run||['completed','failed'].includes(run.status))return;const timer=setTimeout(async()=>{try{const r=await fetch('/api/live?id='+run.id);const j=await r.json();if(!r.ok)throw Error(j.error);setRun(j)}catch(e){setError(e instanceof Error?e.message:'조회 실패')}},2500);return()=>clearTimeout(timer)},[run]);
 return <section className="panel" style={{padding:20,marginBottom:20}}><h3>HumanEval 새 벤치마크 실행</h3><p>두 수 더하기 · 문자열 길이 · 삼각형 넓이 · 글자 포함 필터를 세 모델에서 실행합니다. JSON 입력 시 문제 ID에 해당하는 공식 문제·테스트를 사용합니다.</p><button className="button primary" disabled={busy||!!run&&!['completed','failed'].includes(run.status)} onClick={()=>void start()}>네 문제 실제 실행</button>{error&&<p role="alert">{error}</p>}{run&&<><p role="status">{run.status} · {run.rows.length}/{run.total} · {run.id}</p>{run.error&&<p>{run.error}</p>}<details open><summary>문제별 채점 기록</summary><table><thead><tr><th>모델 / 문제</th><th>채점</th><th>응답 시간</th></tr></thead><tbody>{run.rows.map(r=><tr key={r.model+r.task_id}><td>{r.model} / {r.task_id}</td><td>{r.passed?'통과':r.error||'실패'}</td><td>{r.time_ms===null?'미측정':`${r.time_ms}ms`}</td></tr>)}</tbody></table></details></>}</section>
}
